### ISSUE TITLE
useCurrentAccountのidをtokenからそのまま撮ってしまっている

### ISSUE THREAD

**Issue by mackeee-orange** [westlag114/react-rails-app_client#16]
![Screenshot from 2021-06-17 03-55-00](https://user-images.githubusercontent.com/12053974/122276920-4183ec80-cf20-11eb-9aba-4b7ae34faef2.png)

`id = token` が間違っていると思う

**Comment by westlag114** [comment]
仕様っすね。
詳しくは忘れたけどダミーデータだとうまくパースできないからとかな理由だった気がする
